# Generated by Django 5.2.17 on 2026-08-19 16:55
# Required bridge migration: 0009 and later migrations depend on this file.
# Keep it in GitHub even though it only updates field metadata/choices.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("control", "0007_device_lan_clients")]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="activation_method",
            field=models.CharField(choices=[("password", "Login va parol"), ("key", "Aktivatsiya kaliti")], default="password", max_length=12),
        ),
        migrations.AlterField(
            model_name="device",
            name="mode",
            field=models.CharField(choices=[("owner", "Do‘kon egasi kompyuteri"), ("pos", "Sotuvchi / Kassa"), ("warehouse", "Omborchi"), ("manager", "Menejer"), ("universal", "Universal / maqom almashtirish"), ("read_only", "Faqat ko‘rish")], max_length=20),
        ),
        migrations.AlterField(
            model_name="device",
            name="status",
            field=models.CharField(choices=[("pending", "Tasdiq kutilmoqda"), ("active", "Faol"), ("blocked", "Bloklangan"), ("revoked", "Ruxsati bekor qilingan")], db_index=True, default="pending", max_length=12),
        ),
        migrations.AlterField(
            model_name="deviceenrollment",
            name="mode",
            field=models.CharField(choices=[("owner", "Do‘kon egasi kompyuteri"), ("pos", "Sotuvchi / Kassa"), ("warehouse", "Omborchi"), ("manager", "Menejer"), ("universal", "Universal / maqom almashtirish"), ("read_only", "Faqat ko‘rish")], default="pos", max_length=20),
        ),
        migrations.AlterField(
            model_name="store",
            name="status",
            field=models.CharField(choices=[("trial", "Sinov muddati"), ("active", "Faol"), ("suspended", "Vaqtincha to‘xtatilgan"), ("closed", "Yopilgan")], db_index=True, default="trial", max_length=12),
        ),
    ]
