# Generated by Django 5.2.17 on 2026-08-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("control", "0008_alter_device_activation_method_alter_device_mode_and_more")]

    operations = [
        migrations.CreateModel(
            name="NotificationReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_id", models.UUIDField(unique=True)),
                ("event", models.CharField(max_length=40)),
                ("delivered_to", models.JSONField(blank=True, default=list)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notification_receipts", to="control.store")),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [models.Index(fields=["store", "event", "created_at"], name="control_not_store_i_b38fb3_idx")],
            },
        ),
    ]
