# Generated by Django 5.2.17 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("control", "0009_notificationreceipt")]

    operations = [
        migrations.AddField(
            model_name="store",
            name="pos_session_expires_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="pos_session_unlimited",
            field=models.BooleanField(default=True),
        ),
    ]
